### ISSUE TITLE
How to install this tool

### ISSUE THREAD

**Issue by Gaozhongpai** [raynardj/ray#2]
May I ask how to install this 'ray' tool?

**Comment by shwetagodbole** [comment]
Hello Sir , 
when I am tying to import it is shooting this error. 
from ray.kmean_torch import kmeans_core
ModuleNotFoundError: No module named 'ray.kmean_torch'

**Comment by David-Degnan** [comment]
So....was this tool ever installed? I am also getting the "no module named 'ray.kmean_torch'" error.
